### ISSUE TITLE
Concern about maintainability

### ISSUE THREAD

**Issue by rogerorr** [jbcoe/iso_cpp_extension_methods#4]
Under "motivation" we mention concern over the impact such changes might have on existing code. While this is true, some of the proposals do not break _existing_ code; but we are still concerned about the maintainability of code relying on uniform call syntax and the difficulties that library implementors might have when trying to make changes to existing libraries without knowledge of the code bases where they are used.

**Comment by jbcoe** [comment]
I think that you understand this issue better than me. I agree that it's worth mentioning.

**Comment by rogerorr** [comment]
I've extended the second paragraph in "Motivation" to try and capture this concern.
