### ISSUE TITLE
Get paper number and update title

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/iso_cpp_extension_methods#5]
Paper number needs requesting from John Spicer.

Title section needs updating with paper number, date and ISO details.

**Comment by jbcoe** [comment]
I'm very unlikely to make it to Kona.

If you're happy presenting the paper maybe you're happy getting the number too?

**Comment by rogerorr** [comment]
will do

**Comment by rogerorr** [comment]
I'd gathered you were unlikely to make Kona; which is a shame. I'll try to give you warning if and when we get an "airing".

**Comment by rogerorr** [comment]
John replied: 
"P0079.

This will be published as P00xxR0 (revision 0).   If you submit an updated version at some point, it will still be P00xx, but will be revision 1.

The revision numbers only change when a document is submitted for a mailing.

As before, documents circulated as drafts should have D numbers (D00xx).  Only documents for publication should have the P numbers."

Have added D0079_00 to the doc; when we think it's ready I can change to P0079_00, produce the PDF and bump the number to P0079_01 ...

**Comment by rogerorr** [comment]
Release v0.0 created for P0079_00

**Comment by rogerorr** [comment]
I managed to confuse the new revision scheme, based on an "R" delimiter, with my client's, based on "_". Am checking with John Spicer.

**Comment by rogerorr** [comment]
Re-released v0.0 as P0079R0 and new draft to be D0079R1
